### ISSUE TITLE
Build Fail Centos 7.6 3.10 kernel - No APIClient Implementation

### ISSUE THREAD

**Issue by Rob-Wal** [docker/cli#1668]
Trying to build 18.09.01 and even 18.09.0 cli on Centos 7.6 running Kernel 3.10.0-957.5.1.el7.x86_64 fails with *Client does not implement APIClient (missing SwarmUpdate method.

What are the requirements to build docker cli? I think it would be a good idea to put those in the readme or start a wiki page.

I was able to build with 4.20.7-1.el.elrepo.x86_64 kernel.

[root@Cen-Docker01 cli-18.09.1]$ docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
[root@Cen-Docker01 cli-18.09.1]$

[root@Cen-Docker01 cli-18.09.1]$ make -f docker.Makefile binary-windows
docker build  -t docker-cli-cross -f ./dockerfiles/Dockerfile.cross .
Sending build context to Docker daemon  39.03MB
Step 1/3 : FROM    dockercore/golang-cross:1.10.6@sha256:2054e793010774e9dbafc808dd550a99f8468013731728bea7fce56681510078
 ---> 6d3d677b448c
Step 2/3 : ENV     DISABLE_WARN_OUTSIDE_CONTAINER=1
 ---> Using cache
 ---> 97cd6307f8d0
Step 3/3 : WORKDIR /go/src/github.com/docker/cli
 ---> Using cache
 ---> 92d78d9413e7
Successfully built 92d78d9413e7
Successfully tagged docker-cli-cross:latest
docker run --rm -e VERSION=18.09.0-dev -e GITCOMMIT -e PLATFORM -v "/root/docker-vscode/cli-18.09.1":/go/src/github.com/docker/cli docker-cli-cross make binary-windows
./scripts/build/windows
Generating windows resources
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:11: digit exceeds base
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:12: digit exceeds base
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:11: digit exceeds base
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:12: digit exceeds base
Building build/docker-windows-amd64
# github.com/docker/cli/vendor/github.com/docker/docker/client
vendor/github.com/docker/docker/client/interface_stable.go:10:5: cannot use Client literal (type *Client) as type APIClient in assignment:
        *Client does not implement APIClient (missing SwarmUpdate method)
Makefile:39: recipe for target 'binary-windows' failed
make: *** [binary-windows] Error 2
make: *** [binary-windows] Error 2

**Comment by thaJeztah** [comment]
closing as stale
