### ISSUE TITLE
docker/compose/v5 will not compile with v29.3.0+incompatible

### ISSUE THREAD

**Issue by pedantic79** [docker/cli#6877]
### Description

Compiling with `v29.3.0+incompatible` produces compilation error when including `github.com/docker/compose/v5 v5.1.1`.

```
../go/pkg/mod/github.com/docker/cli@v29.3.0+incompatible/cli/command/container/tty.go:63:23: cannot range over 10 (untyped int constant): requires go1.22 or later (-lang was set to go1.16; check go.mod)
```

This makes it impossible to use docker/compose as you need `docker/cli` to initialize the `ComposeService`

### Reproduce

I have a very small reproduce of this: https://github.com/pedantic79/docker-bug/tree/main

Where the compilation error will occur.

go.mod contains

```
require (
	github.com/docker/cli v29.3.0+incompatible
	github.com/docker/compose/v5 v5.1.1
)
```

main.go contains
```
func main() {
	dockerCli, _ := command.NewDockerCli()
	composeService, _ := compose.NewComposeService(dockerCli)
	fmt.Println(composeService) // avoid compiler complaining about unused variable
}
```

### Expected behavior

Program to compile

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

### Additional Info

I can pin to `v29.2.1+incompatible` and that fixes the issue, as that version doesn't use the `for retry := range 10` that was introduced in `v29.3.0+incompatible`

**Comment by thaJeztah** [comment]
Thanks for reporting; this is a duplicate of https://github.com/docker/cli/issues/6852, and fixed in https://github.com/docker/cli/pull/6854, which will be in the upcoming patch release.

**Comment by pedantic79** [comment]
@thaJeztah I can open a new bug for this, but the latest commit (7922984) will produce a similar but different bug

```
go build main.go
# github.com/docker/cli/cli-plugins/hooks
../go/pkg/mod/github.com/docker/cli@v29.3.1-0.20260319144415-7922984193b2+incompatible/cli-plugins/hooks/template.go:25:19: predeclared any requires go1.18 or later (-lang was set to go1.16; check go.mod)
../go/pkg/mod/github.com/docker/cli@v29.3.1-0.20260319144415-7922984193b2+incompatible/cli-plugins/hooks/template.go:26:19: predeclared any requires go1.18 or later (-lang was set to go1.16; check go.mod)
```

It does build correctly with (5d8cc2c) new commits seem to introduce this.

**Comment by thaJeztah** [comment]
Ugh; that's on master I think, or also on the 29.x branch? Let me double check (I have a PR pending to validate as part of CI while we're still in this horrible "not a real module" situation)

**Comment by pedantic79** [comment]
On master. Just checked with (9637f1b)

```
go build main.go
# github.com/docker/cli/cli-plugins/hooks
../go/pkg/mod/github.com/docker/cli@v29.3.1-0.20260325142216-9637f1b3648f+incompatible/cli-plugins/hooks/template.go:25:19: predeclared any requires go1.18 or later (-lang was set to go1.16; check go.mod)
../go/pkg/mod/github.com/docker/cli@v29.3.1-0.20260325142216-9637f1b3648f+incompatible/cli-plugins/hooks/template.go:26:19: predeclared any requires go1.18 or later (-lang was set to go1.16; check go.mod)
```

**Comment by pedantic79** [comment]
(c2be9cc) On 29.x branch is okay.

**Comment by thaJeztah** [comment]
Thanks! Yes, I see it failing in https://github.com/docker/cli/pull/4723 (which is good news that it works 😂). It's really whack-a-mole with Go downgrading go language versions for individual files.

**Comment by pedantic79** [comment]
Yep. I can keep my code pinned to the last working version. Just wanted to make sure it's known so we don't have another broken version released in the future.

**Comment by thaJeztah** [comment]
- opened https://github.com/docker/cli/pull/6888 for master 👍
